//Users
export const USER_REQUEST_INIT = "USER_REQUEST_INIT";
export const CLOSE_USER_FORM_RESET = "CLOSE_FORM_RESET";
export const GET_USER_PROFILE_INIT = "GET_USER_PROFILE_INIT";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";
export const UPDATE_USER_ABOUT_SUCCESS = "UPDATE_USER_ABOUT_SUCCESS";
export const UPDATE_USER_ABOUT_FAILURE = "UPDATE_USER_ABOUT_FAILURE";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_FAILURE = "UPDATE_USER_PASSWORD_FAILURE";

//Posts
export const POST_REQUEST_INIT = "POST_REQUEST_INIT";
export const CLOSE_POST_FORM_RESET = "CLOSE_POST_FORM_RESET";
export const GET_POSTS = "GET_POSTS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

//Drafts
export const DRAFT_REQUEST_INIT = "DRAFT_REQUEST_INIT";
export const CLOSE_DRAFT_FORM_RESET = "CLOSE_DRAFT_FORM_RESET";
export const GET_DRAFTS_SUCCESS = "GET_DRAFTS_SUCCESS";
export const GET_DRAFTS_FAILURE = "GET_DRAFTS_FAILURE";
export const CREATE_DRAFT_SUCCESS = "CREATE_DRAFT_SUCCESS";
export const CREATE_DRAFT_FAILURE = "CREATE_DRAFT_FAILURE";
export const UPDATE_DRAFT_SUCCESS = "UPDATE_DRAFT_SUCCESS";
export const UPDATE_DRAFT_FAILURE = "UPDATE_DRAFT_FAILURE";
export const PUBLISH_DRAFT_SUCCESS = "PUBLISH_DRAFT_SUCCESS";
export const PUBLISH_DRAFT_FAILURE = "PUBLISH_DRAFT_FAILURE";
export const DELETE_DRAFT_SUCCESS = "DELETE_DRAFT_SUCCESS";
export const DELETE_DRAFT_FAILURE = "DELETE_DRAFT_FAILURE";

//Comments
export const COMMENT_REQUEST_INIT = "COMMENT_REQUEST_INIT";
export const CLOSE_COMMENT_FORM_RESET = "CLOSE_COMMENT_FORM_RESET";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILURE = "UPDATE_COMMENT_FAILURE";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

//Auth
export const CHECK_AUTH = "CHECK_AUTH";
export const AUTH_USER_INIT = "AUTH_USER_INIT";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAILURE = "SIGNIN_USER_FAILURE";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const SIGNOUT_USER_FAILURE = "SIGNOUT_USER_FAILURE";
